Repository appsignal/appsignal-elixir-phoenix, pull requests merged in 2024-04, with the labels that each got.

#85 Determine action name from ActionClauseErrors
  .changesets/set-action-name-for-phoenix-actionclauseerror-errors.md
  lib/appsignal_phoenix/event_handler.ex
  test/appsignal_phoenix/event_handler_test.exs
Labels: enhancement

#86 Fix warnings for unused variables
  lib/appsignal_phoenix/event_handler.ex
Labels: bug

#87 Add changeset for unused warnings fix
  .changesets/fix-unused-variables-warnings.md
Labels: chore
