Repository appsignal/appsignal-elixir-phoenix, pull requests merged in 2024-06, with the labels that each got.

#88 Allow custom action names to be set
  .changesets/allow-custom-action-names.md
  lib/appsignal_phoenix/event_handler.ex
  mix.exs
  test/appsignal_phoenix/event_handler_test.exs
Labels: enhancement

#89 Notify changelog repository of new releases
  .github/workflows/create_release_from_tag.yml
Labels: dev happiness

#90 Handle :phoenix, :endpoint events in EventHandler
  .changesets/add-endpoint-events-to-phoenix-request-traces.md
  lib/appsignal_phoenix/event_handler.ex
  test/appsignal_phoenix/event_handler_test.exs
Labels: feature

#93 Move CI to Github actions
  .github/workflows/ci.yaml
  .semaphore/semaphore.yml
  .semaphore/semaphore.yml.erb
  .semaphore/versions.rb
  bin/setup
  lib/appsignal_phoenix/event_handler.ex
  script/generate_ci_matrix
  script/lint_git
  script/validate_ci_matrix
Labels: chore

#94 Don't use Appsignal.Utils for logging & compiling
  lib/appsignal_phoenix/channel.ex
  lib/appsignal_phoenix/event_handler.ex
  lib/appsignal_phoenix/live_view.ex
  lib/appsignal_phoenix/template.ex
  lib/appsignal_phoenix/view.ex
Labels: chore
